/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef XC_ENGINE_API
#define XC_ENGINE_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern XC_ENGINE_API FName XC_ENGINE_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class XC_ENGINE_API AXC_PrimitiveActor : public AActor
{
public:
    BITFIELD bNoLineCheck:1 GCC_PACK(4);
    BITFIELD bNoPointCheck:1;
    BITFIELD bNoEncroachmentCheck:1;
    BITFIELD bNoExtentCheck:1;
    BITFIELD bForceZeroExtent:1;
    BITFIELD bFallBackToCylinder:1;
    BITFIELD bBackTrace:1;
    INT ActorChannel GCC_PACK(4);
    DECLARE_CLASS(AXC_PrimitiveActor,AActor,0,XC_Engine)
    NO_DEFAULT_CONSTRUCTOR(AXC_PrimitiveActor)
};


class XC_ENGINE_API AXC_PrimitiveMesh : public AXC_PrimitiveActor
{
public:
    TArray<FLOAT> SNorm;
    INT TVerts;
    INT TVertsCount;
    INT TPlanes;
    INT TPlanesCount;
    DECLARE_CLASS(AXC_PrimitiveMesh,AXC_PrimitiveActor,0,XC_Engine)
    NO_DEFAULT_CONSTRUCTOR(AXC_PrimitiveMesh)
};


class XC_ENGINE_API AXC_PrimitivePlane : public AXC_PrimitiveActor
{
public:
    BITFIELD bBlockOutgoing:1 GCC_PACK(4);
    BITFIELD bBlockIncoming:1;
    BITFIELD bUseMyLocation:1;
    BITFIELD bUseMyRotation:1;
    BITFIELD bSolidifyBehindPlane:1;
    FPlane iPlane GCC_PACK(4);
    FLOAT iHAxis;
    FVector CachedLocation;
    FRotator CachedRotation;
    DECLARE_CLASS(AXC_PrimitivePlane,AXC_PrimitiveActor,0,XC_Engine)
    NO_DEFAULT_CONSTRUCTOR(AXC_PrimitivePlane)
};


class XC_ENGINE_API AXC_PrimitiveSphere : public AXC_PrimitiveActor
{
public:
    BITFIELD bHollow:1 GCC_PACK(4);
    BITFIELD bNoHollowFrontHits:1;
    DECLARE_CLASS(AXC_PrimitiveSphere,AXC_PrimitiveActor,0,XC_Engine)
    NO_DEFAULT_CONSTRUCTOR(AXC_PrimitiveSphere)
};


class XC_ENGINE_API AXC_ConnectionHandler : public AActor
{
public:
    FLOAT DatalessTimeout;
    FLOAT CriticalTimeout;
    INT CriticalConnCount;
    INT ExtraTCPQueries;
    DECLARE_CLASS(AXC_ConnectionHandler,AActor,0|CLASS_Config,XC_Engine)
    NO_DEFAULT_CONSTRUCTOR(AXC_ConnectionHandler)
};


class XC_ENGINE_API UXC_EditorLoader : public UObject
{
public:
    DECLARE_CLASS(UXC_EditorLoader,UObject,0,XC_Engine)
    NO_DEFAULT_CONSTRUCTOR(UXC_EditorLoader)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
